name: Build & Push to Dockerhub

on:
  push:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:

    - name: Build & Push to Dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mcnamee/pentest-toolkit
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
