name: Build & Push to Dockerhub

on:
  push:
    tags:
      - 0.*
      - 1.*
      - 2.*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - name: Build & Push to Dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mcnamee/pentest-toolkit
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}

    - name: Sync Readme to Dockerhub
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mcnamee/pentest-toolkit
        readme: "./README.md"
