name: 'SSH4Me'
author: 'jisan09'
description: 'Build SSH tunnel using ngrok over workflow'

runs:
  using: 'composite'
  steps:
    - name: 'Set up Docker'
      shell: bash
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh

    - name: 'Build Docker image'
      shell: bash
      run: |
        docker build -t lscr.io/linuxserver/kali-linux:latest  .

    - name: 'Run Docker container'
      shell: bash
      run: docker run --rm --privileged multiarch/qemu-user-static:register --reset

branding:
  icon: 'terminal'
  color: 'gray-dark'
